/**
 * Schemas: data structure definitions for OpenForm
 *
 * These types correspond to JSON schemas defined in @open-form/schemas.
 * For runtime types (filled forms, parties, etc.), see ../runtime
 */

// Primitives (correspond to schemas in @open-form/schemas)
export type {
  Money,
  Address,
  Phone,
  Person,
  Organization,
  Coordinate,
  Bbox,
  Duration,
  Identification,
  Metadata,
  Signature,
  Attachment,
} from "./primitives";

// Artifact types (includes shared logic types)
export type {
  // Logic types
  CondExpr,
  BaseLogicExpression,
  BooleanLogicExpression,
  StringLogicExpression,
  NumberLogicExpression,
  IntegerLogicExpression,
  PercentageLogicExpression,
  RatingLogicExpression,
  DateLogicExpression,
  TimeLogicExpression,
  DatetimeLogicExpression,
  DurationLogicExpression,
  MoneyLogicExpressionValue,
  AddressLogicExpressionValue,
  PhoneLogicExpressionValue,
  CoordinateLogicExpressionValue,
  BboxLogicExpressionValue,
  PersonLogicExpressionValue,
  OrganizationLogicExpressionValue,
  IdentificationLogicExpressionValue,
  MoneyLogicExpression,
  AddressLogicExpression,
  PhoneLogicExpression,
  CoordinateLogicExpression,
  BboxLogicExpression,
  PersonLogicExpression,
  OrganizationLogicExpression,
  IdentificationLogicExpression,
  ScalarLogicExpression,
  ObjectLogicExpression,
  LogicExpression,
  ScalarLogicType,
  ObjectLogicType,
  LogicExpressionType,
  LogicSection,
  // Shared types
  ArtifactBase,
  Layer,
  InlineLayer,
  FileLayer,
  Bindings,
  // Document
  Document,
  // Checklist
  BooleanStatusSpec,
  EnumStatusOption,
  EnumStatusSpec,
  StatusSpec,
  ChecklistItem,
  Checklist,
  // Bundle
  BundleContentItem,
  InlineBundleItem,
  PathBundleItem,
  RegistryBundleItem,
  Bundle,
  // Form
  Form,
  BaseField,
  FieldsetField,
  FormField,
  TextField,
  BooleanField,
  NumberField,
  CoordinateField,
  BboxField,
  MoneyField,
  AddressField,
  PhoneField,
  DurationField,
  EmailField,
  UuidField,
  UriField,
  EnumField,
  DateField,
  DatetimeField,
  TimeField,
  PersonField,
  OrganizationField,
  IdentificationField,
  MultiselectField,
  PercentageField,
  RatingField,
  FormFieldset,
  FormAnnex,
  FormParty,
  FormSignature,
  // Unions
  Artifact,
} from "./artifacts";
