packages:
  - "apps/*"
  - "packages/*"
  - "platform/apps/*"
  - "platform/packages/*"
  - "incubator/apps/*"
  - "incubator/packages/*"
  - "artifacts/*"

catalog:
  tsup: "^8.4.0"
  "@types/node": "^22.15.3"
  "@types/react": "19.2.7"
  "@types/react-dom": "19.2.3"
  "@vitest/coverage-v8": "^2.1.8"
  vitest: "^2.1.8"
  typescript: "5.9.2"
  eslint: "^9.34.0"
  ajv: "^8.17.1"
  ajv-formats: "^3.0.1"
  yaml: "^2.8.1"

  "@neondatabase/serverless": "^1.0.2"
  "@orpc/contract": "^1.10.3"
  date-fns: "^4.1.0"
  drizzle-orm: "^0.44.6"
  fast-deep-equal: "^3.1.3"
  lodash: "^4.17.21"
  "lucide-react": "^0.560.0"
  nanoid: "^5.1.6"
  "@phosphor-icons/react": "^2.1.10"
  react: "19.2.1"
  react-dom: "19.2.1"
  semver: "^7.7.3"
  uuid: "^13.0.0"
  validator: "^13.15.15"
  yaml-diff-patch: "^2.0.0"
  zod: "^4.1.12"
  "@workos-inc/node": "^7.81.0"
  dotenv: "^17.2.3"
  "@types/dotenv": "^8.2.3"
  tsx: "^4.20.6"
  stripe: "^20.0.0"
